# Workflow to create a pull request merging changes from the master branch into the production branch upon release.

name: Create Release Pull Request

# Trigger the workflow when a release is published
on:
  # release:
  #   types: [published]
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      # Step 2: Set up Git with a consistent user identity for commits
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Check out the master branch and pull the latest changes
      - name: Check out master branch
        run: |
          git checkout master
          git pull origin master

      # Step 4: Check out the production branch and reset it to the master branch
      - name: Reset production branch
        run: |
          git checkout branch_for_release_test
          git reset --hard origin/master
    
      # Step 5: Push the changes to the production branch
      - name: Push changes to production branch
        run: |
          git push origin branch_for_release_test --force

      # Step 6: Create a pull request to merge master into the production branch
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
          commit-message: 'Merge master branch into production'
          title: 'Release Merge: ${{ github.event.release.tag_name }}' # Title of the pull request
          body: 'This pull request merges the master branch into the production branch.' # Body content of the pull request
          base: branch_for_release_test # The base branch of the pull request
          head: master # The head branch of the pull request
