# Workflow to create a pull request merging changes from the main branch into the production branch upon release.

name: Create Release Pull Request

# Trigger the workflow when a release is published
# on:
#   release:
#     types: [published]

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:  
          ref: release

      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
    
      # Step 7: Create a pull request to merge main into production
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
          commit-message: 'Merge main branch into production'
          title: 'Release Merge: ${{ github.event.release.tag_name }}' # Title of the pull request
          body: 'This pull request merges the main branch into the production branch.' # Body content of the pull request
          base: branch_for_release_test # The base branch of the pull request
          head: master # The head branch of the pull request
