name: Create Pull Request to Merge Main into Master

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: peter-evans/create-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: "master"
          PULL_REQUEST_BRANCH: "branch_for_release_test"
          BASE: "branch_for_release_test"
