name: Merge Latest Release to Different Branch

on:
  release:
    types: [published]

jobs:
  merge-release:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release version
        id: get_release
        run: echo "::set-output name=version::$(curl -sSL https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge latest release into target branch'
          title: 'Merge Latest Release: ${{ steps.get_release.outputs.version }}'
          body: 'This pull request merges the latest release into the target branch.'
          branch: branch_for_release_test # The target branch where you want to merge changes
          base: master # The base branch of the pull request
          head: 'refs/tags/${{ steps.get_release.outputs.version }}' # The release version as the source branch
