name: Merge latest release from main to production Branch

on:
  # workflow_dispatch:   #Manual trigger for testing
  release:
    types: [published]  #Triggers when a release is published

jobs:
  release-merge-to-production:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "PULL_REQUEST_TITLE=Release Merge from $PULL_REQUEST_FROM_BRANCH to $PULL_REQUEST_BRANCH" >> $GITHUB_ENV
          echo "PULL_REQUEST_BODY='This pull request merges the latest release into $PULL_REQUEST_BRANCH" >> $GITHUB_ENV

      - name: create-pull-request
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: "master"
          PULL_REQUEST_BRANCH: "production"
          PULL_REQUEST_FROM_BRANCH: "master"
        with:
          title: "${{ env.PULL_REQUEST_TITLE }}"
          body: "${{ env.PULL_REQUEST_BODY }}"
      
         
