name: My Workflow

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest

    env:
      PRODUCTION: "main"
      MAIN: "production"

    steps:
      - name: Print environment variables
        run: |
          echo "MY_VARIABLE is $RELEASE_TOKEN"
          echo "ANOTHER_VARIABLE is $MAIN"
